// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetRegionServerLSN.proto

package org.splicemachine.capstone;

public final class GetRegionServerLSNProtos {
  private GetRegionServerLSNProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GetRegionServerLSNRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code GetRegionServerLSNRequest}
   */
  public static final class GetRegionServerLSNRequest extends
      com.google.protobuf.GeneratedMessage
      implements GetRegionServerLSNRequestOrBuilder {
    // Use GetRegionServerLSNRequest.newBuilder() to construct.
    private GetRegionServerLSNRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetRegionServerLSNRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetRegionServerLSNRequest defaultInstance;
    public static GetRegionServerLSNRequest getDefaultInstance() {
      return defaultInstance;
    }

    public GetRegionServerLSNRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetRegionServerLSNRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.splicemachine.capstone.GetRegionServerLSNProtos.internal_static_GetRegionServerLSNRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.splicemachine.capstone.GetRegionServerLSNProtos.internal_static_GetRegionServerLSNRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest.class, org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<GetRegionServerLSNRequest> PARSER =
        new com.google.protobuf.AbstractParser<GetRegionServerLSNRequest>() {
      public GetRegionServerLSNRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetRegionServerLSNRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetRegionServerLSNRequest> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest)) {
        return super.equals(obj);
      }
      org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest other = (org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest) obj;

      boolean result = true;
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetRegionServerLSNRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.splicemachine.capstone.GetRegionServerLSNProtos.internal_static_GetRegionServerLSNRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.splicemachine.capstone.GetRegionServerLSNProtos.internal_static_GetRegionServerLSNRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest.class, org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest.Builder.class);
      }

      // Construct using org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.splicemachine.capstone.GetRegionServerLSNProtos.internal_static_GetRegionServerLSNRequest_descriptor;
      }

      public org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest getDefaultInstanceForType() {
        return org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest.getDefaultInstance();
      }

      public org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest build() {
        org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest buildPartial() {
        org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest result = new org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest) {
          return mergeFrom((org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest other) {
        if (other == org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GetRegionServerLSNRequest)
    }

    static {
      defaultInstance = new GetRegionServerLSNRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GetRegionServerLSNRequest)
  }

  public interface GetRegionServerLSNReponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .GetRegionServerLSNReponse.Result result = 1;
    /**
     * <code>repeated .GetRegionServerLSNReponse.Result result = 1;</code>
     */
    java.util.List<org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result>
        getResultList();
    /**
     * <code>repeated .GetRegionServerLSNReponse.Result result = 1;</code>
     */
    org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result getResult(int index);
    /**
     * <code>repeated .GetRegionServerLSNReponse.Result result = 1;</code>
     */
    int getResultCount();
    /**
     * <code>repeated .GetRegionServerLSNReponse.Result result = 1;</code>
     */
    java.util.List<? extends org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.ResultOrBuilder>
        getResultOrBuilderList();
    /**
     * <code>repeated .GetRegionServerLSNReponse.Result result = 1;</code>
     */
    org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.ResultOrBuilder getResultOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code GetRegionServerLSNReponse}
   */
  public static final class GetRegionServerLSNReponse extends
      com.google.protobuf.GeneratedMessage
      implements GetRegionServerLSNReponseOrBuilder {
    // Use GetRegionServerLSNReponse.newBuilder() to construct.
    private GetRegionServerLSNReponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetRegionServerLSNReponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetRegionServerLSNReponse defaultInstance;
    public static GetRegionServerLSNReponse getDefaultInstance() {
      return defaultInstance;
    }

    public GetRegionServerLSNReponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetRegionServerLSNReponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                result_ = new java.util.ArrayList<org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result>();
                mutable_bitField0_ |= 0x00000001;
              }
              result_.add(input.readMessage(org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          result_ = java.util.Collections.unmodifiableList(result_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.splicemachine.capstone.GetRegionServerLSNProtos.internal_static_GetRegionServerLSNReponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.splicemachine.capstone.GetRegionServerLSNProtos.internal_static_GetRegionServerLSNReponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.class, org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Builder.class);
    }

    public static com.google.protobuf.Parser<GetRegionServerLSNReponse> PARSER =
        new com.google.protobuf.AbstractParser<GetRegionServerLSNReponse>() {
      public GetRegionServerLSNReponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetRegionServerLSNReponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetRegionServerLSNReponse> getParserForType() {
      return PARSER;
    }

    public interface ResultOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional uint64 lsn = 1;
      /**
       * <code>optional uint64 lsn = 1;</code>
       */
      boolean hasLsn();
      /**
       * <code>optional uint64 lsn = 1;</code>
       */
      long getLsn();

      // optional string regionName = 2;
      /**
       * <code>optional string regionName = 2;</code>
       */
      boolean hasRegionName();
      /**
       * <code>optional string regionName = 2;</code>
       */
      java.lang.String getRegionName();
      /**
       * <code>optional string regionName = 2;</code>
       */
      com.google.protobuf.ByteString
          getRegionNameBytes();
    }
    /**
     * Protobuf type {@code GetRegionServerLSNReponse.Result}
     */
    public static final class Result extends
        com.google.protobuf.GeneratedMessage
        implements ResultOrBuilder {
      // Use Result.newBuilder() to construct.
      private Result(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Result(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Result defaultInstance;
      public static Result getDefaultInstance() {
        return defaultInstance;
      }

      public Result getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Result(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                lsn_ = input.readUInt64();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                regionName_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.splicemachine.capstone.GetRegionServerLSNProtos.internal_static_GetRegionServerLSNReponse_Result_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.splicemachine.capstone.GetRegionServerLSNProtos.internal_static_GetRegionServerLSNReponse_Result_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result.class, org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result.Builder.class);
      }

      public static com.google.protobuf.Parser<Result> PARSER =
          new com.google.protobuf.AbstractParser<Result>() {
        public Result parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Result(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Result> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional uint64 lsn = 1;
      public static final int LSN_FIELD_NUMBER = 1;
      private long lsn_;
      /**
       * <code>optional uint64 lsn = 1;</code>
       */
      public boolean hasLsn() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint64 lsn = 1;</code>
       */
      public long getLsn() {
        return lsn_;
      }

      // optional string regionName = 2;
      public static final int REGIONNAME_FIELD_NUMBER = 2;
      private java.lang.Object regionName_;
      /**
       * <code>optional string regionName = 2;</code>
       */
      public boolean hasRegionName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string regionName = 2;</code>
       */
      public java.lang.String getRegionName() {
        java.lang.Object ref = regionName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            regionName_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string regionName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRegionNameBytes() {
        java.lang.Object ref = regionName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          regionName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        lsn_ = 0L;
        regionName_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeUInt64(1, lsn_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getRegionNameBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(1, lsn_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getRegionNameBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result)) {
          return super.equals(obj);
        }
        org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result other = (org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result) obj;

        boolean result = true;
        result = result && (hasLsn() == other.hasLsn());
        if (hasLsn()) {
          result = result && (getLsn()
              == other.getLsn());
        }
        result = result && (hasRegionName() == other.hasRegionName());
        if (hasRegionName()) {
          result = result && getRegionName()
              .equals(other.getRegionName());
        }
        result = result &&
            getUnknownFields().equals(other.getUnknownFields());
        return result;
      }

      private int memoizedHashCode = 0;
      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        if (hasLsn()) {
          hash = (37 * hash) + LSN_FIELD_NUMBER;
          hash = (53 * hash) + hashLong(getLsn());
        }
        if (hasRegionName()) {
          hash = (37 * hash) + REGIONNAME_FIELD_NUMBER;
          hash = (53 * hash) + getRegionName().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code GetRegionServerLSNReponse.Result}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.ResultOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.splicemachine.capstone.GetRegionServerLSNProtos.internal_static_GetRegionServerLSNReponse_Result_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.splicemachine.capstone.GetRegionServerLSNProtos.internal_static_GetRegionServerLSNReponse_Result_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result.class, org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result.Builder.class);
        }

        // Construct using org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          lsn_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000001);
          regionName_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.splicemachine.capstone.GetRegionServerLSNProtos.internal_static_GetRegionServerLSNReponse_Result_descriptor;
        }

        public org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result getDefaultInstanceForType() {
          return org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result.getDefaultInstance();
        }

        public org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result build() {
          org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result buildPartial() {
          org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result result = new org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.lsn_ = lsn_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.regionName_ = regionName_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result) {
            return mergeFrom((org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result other) {
          if (other == org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result.getDefaultInstance()) return this;
          if (other.hasLsn()) {
            setLsn(other.getLsn());
          }
          if (other.hasRegionName()) {
            bitField0_ |= 0x00000002;
            regionName_ = other.regionName_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional uint64 lsn = 1;
        private long lsn_ ;
        /**
         * <code>optional uint64 lsn = 1;</code>
         */
        public boolean hasLsn() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional uint64 lsn = 1;</code>
         */
        public long getLsn() {
          return lsn_;
        }
        /**
         * <code>optional uint64 lsn = 1;</code>
         */
        public Builder setLsn(long value) {
          bitField0_ |= 0x00000001;
          lsn_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional uint64 lsn = 1;</code>
         */
        public Builder clearLsn() {
          bitField0_ = (bitField0_ & ~0x00000001);
          lsn_ = 0L;
          onChanged();
          return this;
        }

        // optional string regionName = 2;
        private java.lang.Object regionName_ = "";
        /**
         * <code>optional string regionName = 2;</code>
         */
        public boolean hasRegionName() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string regionName = 2;</code>
         */
        public java.lang.String getRegionName() {
          java.lang.Object ref = regionName_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            regionName_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string regionName = 2;</code>
         */
        public com.google.protobuf.ByteString
            getRegionNameBytes() {
          java.lang.Object ref = regionName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            regionName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string regionName = 2;</code>
         */
        public Builder setRegionName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          regionName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string regionName = 2;</code>
         */
        public Builder clearRegionName() {
          bitField0_ = (bitField0_ & ~0x00000002);
          regionName_ = getDefaultInstance().getRegionName();
          onChanged();
          return this;
        }
        /**
         * <code>optional string regionName = 2;</code>
         */
        public Builder setRegionNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          regionName_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:GetRegionServerLSNReponse.Result)
      }

      static {
        defaultInstance = new Result(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:GetRegionServerLSNReponse.Result)
    }

    // repeated .GetRegionServerLSNReponse.Result result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private java.util.List<org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result> result_;
    /**
     * <code>repeated .GetRegionServerLSNReponse.Result result = 1;</code>
     */
    public java.util.List<org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result> getResultList() {
      return result_;
    }
    /**
     * <code>repeated .GetRegionServerLSNReponse.Result result = 1;</code>
     */
    public java.util.List<? extends org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.ResultOrBuilder>
        getResultOrBuilderList() {
      return result_;
    }
    /**
     * <code>repeated .GetRegionServerLSNReponse.Result result = 1;</code>
     */
    public int getResultCount() {
      return result_.size();
    }
    /**
     * <code>repeated .GetRegionServerLSNReponse.Result result = 1;</code>
     */
    public org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result getResult(int index) {
      return result_.get(index);
    }
    /**
     * <code>repeated .GetRegionServerLSNReponse.Result result = 1;</code>
     */
    public org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.ResultOrBuilder getResultOrBuilder(
        int index) {
      return result_.get(index);
    }

    private void initFields() {
      result_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < result_.size(); i++) {
        output.writeMessage(1, result_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < result_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, result_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse)) {
        return super.equals(obj);
      }
      org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse other = (org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse) obj;

      boolean result = true;
      result = result && getResultList()
          .equals(other.getResultList());
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getResultCount() > 0) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getResultList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetRegionServerLSNReponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.splicemachine.capstone.GetRegionServerLSNProtos.internal_static_GetRegionServerLSNReponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.splicemachine.capstone.GetRegionServerLSNProtos.internal_static_GetRegionServerLSNReponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.class, org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Builder.class);
      }

      // Construct using org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getResultFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (resultBuilder_ == null) {
          result_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          resultBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.splicemachine.capstone.GetRegionServerLSNProtos.internal_static_GetRegionServerLSNReponse_descriptor;
      }

      public org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse getDefaultInstanceForType() {
        return org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.getDefaultInstance();
      }

      public org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse build() {
        org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse buildPartial() {
        org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse result = new org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse(this);
        int from_bitField0_ = bitField0_;
        if (resultBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            result_ = java.util.Collections.unmodifiableList(result_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.result_ = result_;
        } else {
          result.result_ = resultBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse) {
          return mergeFrom((org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse other) {
        if (other == org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.getDefaultInstance()) return this;
        if (resultBuilder_ == null) {
          if (!other.result_.isEmpty()) {
            if (result_.isEmpty()) {
              result_ = other.result_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureResultIsMutable();
              result_.addAll(other.result_);
            }
            onChanged();
          }
        } else {
          if (!other.result_.isEmpty()) {
            if (resultBuilder_.isEmpty()) {
              resultBuilder_.dispose();
              resultBuilder_ = null;
              result_ = other.result_;
              bitField0_ = (bitField0_ & ~0x00000001);
              resultBuilder_ =
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getResultFieldBuilder() : null;
            } else {
              resultBuilder_.addAllMessages(other.result_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .GetRegionServerLSNReponse.Result result = 1;
      private java.util.List<org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result> result_ =
        java.util.Collections.emptyList();
      private void ensureResultIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          result_ = new java.util.ArrayList<org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result>(result_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result, org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result.Builder, org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.ResultOrBuilder> resultBuilder_;

      /**
       * <code>repeated .GetRegionServerLSNReponse.Result result = 1;</code>
       */
      public java.util.List<org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result> getResultList() {
        if (resultBuilder_ == null) {
          return java.util.Collections.unmodifiableList(result_);
        } else {
          return resultBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .GetRegionServerLSNReponse.Result result = 1;</code>
       */
      public int getResultCount() {
        if (resultBuilder_ == null) {
          return result_.size();
        } else {
          return resultBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .GetRegionServerLSNReponse.Result result = 1;</code>
       */
      public org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result getResult(int index) {
        if (resultBuilder_ == null) {
          return result_.get(index);
        } else {
          return resultBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .GetRegionServerLSNReponse.Result result = 1;</code>
       */
      public Builder setResult(
          int index, org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.set(index, value);
          onChanged();
        } else {
          resultBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .GetRegionServerLSNReponse.Result result = 1;</code>
       */
      public Builder setResult(
          int index, org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.set(index, builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GetRegionServerLSNReponse.Result result = 1;</code>
       */
      public Builder addResult(org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.add(value);
          onChanged();
        } else {
          resultBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .GetRegionServerLSNReponse.Result result = 1;</code>
       */
      public Builder addResult(
          int index, org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.add(index, value);
          onChanged();
        } else {
          resultBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .GetRegionServerLSNReponse.Result result = 1;</code>
       */
      public Builder addResult(
          org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.add(builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GetRegionServerLSNReponse.Result result = 1;</code>
       */
      public Builder addResult(
          int index, org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.add(index, builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GetRegionServerLSNReponse.Result result = 1;</code>
       */
      public Builder addAllResult(
          java.lang.Iterable<? extends org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result> values) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          super.addAll(values, result_);
          onChanged();
        } else {
          resultBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .GetRegionServerLSNReponse.Result result = 1;</code>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          result_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          resultBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .GetRegionServerLSNReponse.Result result = 1;</code>
       */
      public Builder removeResult(int index) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.remove(index);
          onChanged();
        } else {
          resultBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .GetRegionServerLSNReponse.Result result = 1;</code>
       */
      public org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result.Builder getResultBuilder(
          int index) {
        return getResultFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .GetRegionServerLSNReponse.Result result = 1;</code>
       */
      public org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.ResultOrBuilder getResultOrBuilder(
          int index) {
        if (resultBuilder_ == null) {
          return result_.get(index);  } else {
          return resultBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .GetRegionServerLSNReponse.Result result = 1;</code>
       */
      public java.util.List<? extends org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.ResultOrBuilder>
           getResultOrBuilderList() {
        if (resultBuilder_ != null) {
          return resultBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(result_);
        }
      }
      /**
       * <code>repeated .GetRegionServerLSNReponse.Result result = 1;</code>
       */
      public org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result.Builder addResultBuilder() {
        return getResultFieldBuilder().addBuilder(
            org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result.getDefaultInstance());
      }
      /**
       * <code>repeated .GetRegionServerLSNReponse.Result result = 1;</code>
       */
      public org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result.Builder addResultBuilder(
          int index) {
        return getResultFieldBuilder().addBuilder(
            index, org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result.getDefaultInstance());
      }
      /**
       * <code>repeated .GetRegionServerLSNReponse.Result result = 1;</code>
       */
      public java.util.List<org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result.Builder>
           getResultBuilderList() {
        return getResultFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result, org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result.Builder, org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.ResultOrBuilder>
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          resultBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result, org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.Result.Builder, org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.ResultOrBuilder>(
                  result_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        return resultBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:GetRegionServerLSNReponse)
    }

    static {
      defaultInstance = new GetRegionServerLSNReponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GetRegionServerLSNReponse)
  }

  /**
   * Protobuf service {@code GetRegionServerLSNService}
   */
  public static abstract class GetRegionServerLSNService
      implements com.google.protobuf.Service {
    protected GetRegionServerLSNService() {}

    public interface Interface {
      /**
       * <code>rpc getRegionServerLSN(.GetRegionServerLSNRequest) returns (.GetRegionServerLSNReponse);</code>
       */
      public abstract void getRegionServerLSN(
          com.google.protobuf.RpcController controller,
          org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest request,
          com.google.protobuf.RpcCallback<org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new GetRegionServerLSNService() {
        @java.lang.Override
        public  void getRegionServerLSN(
            com.google.protobuf.RpcController controller,
            org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest request,
            com.google.protobuf.RpcCallback<org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse> done) {
          impl.getRegionServerLSN(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getRegionServerLSN(controller, (org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc getRegionServerLSN(.GetRegionServerLSNRequest) returns (.GetRegionServerLSNReponse);</code>
     */
    public abstract void getRegionServerLSN(
        com.google.protobuf.RpcController controller,
        org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest request,
        com.google.protobuf.RpcCallback<org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.splicemachine.capstone.GetRegionServerLSNProtos.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getRegionServerLSN(controller, (org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest)request,
            com.google.protobuf.RpcUtil.<org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getRegionServerLSN(
          com.google.protobuf.RpcController controller,
          org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest request,
          com.google.protobuf.RpcCallback<org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.class,
            org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse getRegionServerLSN(
          com.google.protobuf.RpcController controller,
          org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse getRegionServerLSN(
          com.google.protobuf.RpcController controller,
          org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNRequest request)
          throws com.google.protobuf.ServiceException {
        return (org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.splicemachine.capstone.GetRegionServerLSNProtos.GetRegionServerLSNReponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:GetRegionServerLSNService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_GetRegionServerLSNRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetRegionServerLSNRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_GetRegionServerLSNReponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetRegionServerLSNReponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_GetRegionServerLSNReponse_Result_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetRegionServerLSNReponse_Result_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030GetRegionServerLSN.proto\"\033\n\031GetRegionS" +
      "erverLSNRequest\"y\n\031GetRegionServerLSNRep" +
      "onse\0221\n\006result\030\001 \003(\0132!.GetRegionServerLS" +
      "NReponse.Result\032)\n\006Result\022\013\n\003lsn\030\001 \001(\004\022\022" +
      "\n\nregionName\030\002 \001(\t2i\n\031GetRegionServerLSN" +
      "Service\022L\n\022getRegionServerLSN\022\032.GetRegio" +
      "nServerLSNRequest\032\032.GetRegionServerLSNRe" +
      "ponseB>\n\032org.splicemachine.capstoneB\030Get" +
      "RegionServerLSNProtosH\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_GetRegionServerLSNRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_GetRegionServerLSNRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_GetRegionServerLSNRequest_descriptor,
              new java.lang.String[] { });
          internal_static_GetRegionServerLSNReponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_GetRegionServerLSNReponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_GetRegionServerLSNReponse_descriptor,
              new java.lang.String[] { "Result", });
          internal_static_GetRegionServerLSNReponse_Result_descriptor =
            internal_static_GetRegionServerLSNReponse_descriptor.getNestedTypes().get(0);
          internal_static_GetRegionServerLSNReponse_Result_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_GetRegionServerLSNReponse_Result_descriptor,
              new java.lang.String[] { "Lsn", "RegionName", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
